@base_url = http://localhost:8080/efi-wp-outgoing/api
@contentType = application/json
@cookie = token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjEyMywiYXVkIjoiaHR0cDpcL1wvbG9jYWxob3N0OjgwODBcL2VmaS13cC1vdXRnb2luZyIsImlhdCI6MTAzNjgwMCwiZGF0YSI6eyJ1c2VyX2lkIjoxMjMsIm5hbWUiOiJKb2huIERvZSJ9fQ.5yDn7CXVDM7-vMlHmYM-QR2OQT78mWYbHv50lzSEuLI


###
POST {{base_url}}/auth/register HTTP/1.1
Content-Type: {{contentType}}

{   
    "name": "Admin",
    "username": "admin",
    "password": "admin"
}

###
POST {{base_url}}/auth/login HTTP/1.1
Content-Type: {{contentType}}

{
    "username": "admin",
    "password": "admin"
}

###
POST {{base_url}}/auth/logout HTTP/1.1


### get outgoing
GET {{base_url}}/transactions/outgoings HTTP/1.1
Content-Type: {{contentType}}
Cookie: {{cookie}}


### post ougoing
POST {{base_url}}/transactions/outgoings HTTP/1.1
Content-Type: {{contentType}}
Cookie: {{cookie}}

{
    "branch": "Cainta",
    "trans_id": "123",
    "str_no": "05-00123",
    "date_out": "2021-06-14 12:00:00",
    "date_estimated": "2021-06-15 12:00:00",
    "trucking": "trucking123 new",
    "plate_no": "ABC123",
    "delivered_to": "TIPCO",
    "remarks": "test remarks"
}

###
GET {{base_url}}/transactions/details/123 HTTP/1.1
Content-Type: {{contentType}}
Cookie: {{cookie}}

### insert transaction details
POST {{base_url}}/transactions/createdetails HTTP/1.1
Content-Type: {{contentType}}
Cookie: {{cookie}}

{
    "data":  [
        {
            "wp_outgoing_id": 23,
            "wp_grade": "LCOCC",
            "weight": 3124,
            "bales": 3,
            "remarks": "test remarks"
        },
        {
            "wp_outgoing_id": 23,
            "wp_grade": "LCWL",
            "weight": 2124,
            "bales": 2,
            "remarks": "test remarks"
        }
    ]
}

